Repository Nautilus-Cyberneering/chinese-ideographs, pull requests merged in 2021-11, with the labels that each got.

#100 Add Base image to the repository
  .github/actions/auto-commit-images/.gitignore
  .github/actions/auto-commit-images/Dockerfile
  .github/actions/auto-commit-images/README.md
  .github/actions/auto-commit-images/action.yml
  .github/actions/auto-commit-images/requirements.txt
  .github/actions/auto-commit-images/src/auto_commit/__init__.py
  .github/actions/auto-commit-images/src/auto_commit/auto_commit.py
  .github/actions/auto-commit-images/src/auto_commit/librarian.py
  .github/actions/auto-commit-images/src/main.py
  .github/actions/auto-commit-images/src/test/__init__.py
  .github/actions/auto-commit-images/src/test/auto_commit/__init__.py
  .github/actions/auto-commit-images/src/test/auto_commit/test_auto_commit.py
  .github/actions/auto-commit-images/src/test/auto_commit/test_librarian.py
  .github/actions/auto-commit-push/Dockerfile
  .github/actions/auto-commit-push/README.md
  .github/actions/auto-commit-push/action.yml
  .github/actions/auto-commit-push/src/main.py
  .github/workflows/gold-drawings-processing.yml
  .github/workflows/test-action-autocommit-push.yml
  data/000004/32/.gitignore
  data/000005/32/.gitignore
  data/000005/32/000005-32.600.2.tif.dvc
Labels: enhancement

#103 Trigger import workflow on website on push event in main branch
  .github/workflows/update-website.yml
Labels: enhancement

#107 Add Gold Image: 000000-32.600.2.tif
  data/000000/32/.gitignore
  data/000000/32/000000-32.600.2.tif.dvc
  data/000000/42/.gitignore
  data/000000/42/000000-42.600.2.tif.dvc
Labels: media

#109 Add Gold Image: 000004-32.600.2.tif
  data/000004/32/.gitignore
  data/000004/32/000004-32.600.2.tif.dvc
  data/000004/42/.gitignore
  data/000004/42/000004-42.600.2.tif.dvc
Labels: media

#111 Update Gold Image: 000001-32.600.2.tif
  .github/actions/auto-commit-images/src/auto_commit/auto_commit.py
  .github/workflows/gold-drawings-processing.yml
  data/000001/32/000001-32.600.2.tif.dvc
  data/000001/42/000001-42.600.2.tif.dvc
Labels: media

#113 Update Gold Image: 000002-32.600.2.tif
  data/000002/32/000002-32.600.2.tif.dvc
  data/000002/42/000002-42.600.2.tif.dvc
Labels: media

#115 [#114] Add Gold Image: 000003-32.600.2.tif
  data/000003/32/000003-32.600.2.tif.dvc
  data/000003/42/000003-42.600.2.tif.dvc
Labels: media

#117 Update Gold image: 000005-32.600.2.tif
  data/000005/32/000005-32.600.2.tif.dvc
Labels: media

#120 Add Gold image: 000006-32.600.2.tif
  data/000006/32/.gitignore
  data/000006/32/000006-32.600.2.tif.dvc
  data/000006/42/.gitignore
  data/000006/42/000006-42.600.2.tif.dvc
Labels: media

#104 Markdown linting
  .github/workflows/markdown-lint.yml
  .markdownlint.json
  CONTRIBUTING.md
  README.md
  contrib/github-merge/README.md
  documentation/Contributor_Code_of_Conduct.md
  documentation/Filenames_and_Folder_Structure_Conventions.md
  documentation/Markdown Guideline.md
  documentation/Running_GitHub_Actions_Locally.md
  licensing/agpl-3.0.md
  licensing/cc-by-sa.md
  licensing/old_commits/cc0.md
Labels: enhancement

#129 Add gitflow diagrams
  documentation/Processes_and_Workflows.md
  documentation/gitflows.png
Labels: documentation
